"""empty message

Revision ID: 5cbab6d3fb00
Revises: 44e9bca87f13
Create Date: 2019-02-08 23:56:00.942312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cbab6d3fb00'
down_revision = '44e9bca87f13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'funding', ['id'])
    op.create_unique_constraint(None, 'teams', ['id'])
    op.alter_column('users', 'orcid',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'orcid',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'teams', type_='unique')
    op.drop_constraint(None, 'funding', type_='unique')
    # ### end Alembic commands ###
