"""empty message

Revision ID: 9fd7d1234a51
Revises: 
Create Date: 2019-02-26 12:49:53.760252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd7d1234a51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nrp_area',
    sa.Column('nrp_id', sa.Integer(), nullable=False),
    sa.Column('nrp_title', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('nrp_id'),
    sa.UniqueConstraint('nrp_id')
    )
    op.create_table('proposal_call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deadline_text', sa.String(length=50), nullable=True),
    sa.Column('deadline_time', sa.Date(), nullable=True),
    sa.Column('award_amount', sa.Float(), nullable=False),
    sa.Column('amount_left', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('short_text', sa.String(length=500), nullable=False),
    sa.Column('text_description', sa.Text(), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=False),
    sa.Column('eligibil_text', sa.Text(), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('report_guidelines', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('start_date_end', sa.Date(), nullable=True),
    sa.Column('contact', sa.String(length=75), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_types',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('proposal_call_files',
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prop_id'], ['proposal_call.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposal_themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prop_id', sa.Integer(), nullable=False),
    sa.Column('theme_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['prop_id'], ['proposal_call.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('theme_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(length=25), nullable=False),
    sa.Column('l_name', sa.String(length=30), nullable=False),
    sa.Column('job_title', sa.String(length=50), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('suffix', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('phone_ext', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('orcid', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_type'], ['user_types.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('award_grant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('funding_body', sa.String(length=60), nullable=False),
    sa.Column('funding_programme', sa.String(length=90), nullable=False),
    sa.Column('primary_attrib', sa.String(length=60), nullable=False),
    sa.Column('pi', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['pi'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('primary_attrib')
    )
    op.create_table('awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('awarding_body', sa.String(length=50), nullable=True),
    sa.Column('award_details', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(length=25), nullable=False),
    sa.Column('field_of_study', sa.String(length=30), nullable=False),
    sa.Column('institution', sa.String(length=25), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('year_degree_award', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('employment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('years', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('funding_amt', sa.Float(), nullable=True),
    sa.Column('funding_body', sa.String(length=50), nullable=True),
    sa.Column('programme', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('proposal_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('applicant', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('duration', sa.String(length=60), nullable=False),
    sa.Column('amount_required', sa.Float(), nullable=False),
    sa.Column('nrp_area', sa.Integer(), nullable=False),
    sa.Column('textbox', sa.Text(), nullable=False),
    sa.Column('animal_statement', sa.Text(), nullable=False),
    sa.Column('human_statement', sa.Text(), nullable=False),
    sa.Column('applicant_country', sa.String(length=75), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('lay_abstract', sa.Text(), nullable=False),
    sa.Column('signed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['applicant'], ['users.id'], ),
    sa.ForeignKeyConstraint(['nrp_area'], ['nrp_area.nrp_id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal_call.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('societies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('society_name', sa.String(length=50), nullable=True),
    sa.Column('membership_type', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_collaborators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('organization', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['proposal_application.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('application_files',
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['proposal_application.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('co_applicants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('co_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['proposal_application.id'], ),
    sa.ForeignKeyConstraint(['co_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('pending_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['proposal_application.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposal_draft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('applicant', sa.Integer(), nullable=False),
    sa.Column('draft', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['proposal_application.id'], ),
    sa.ForeignKeyConstraint(['applicant'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rc_team',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('team_desc', sa.Text(), nullable=True),
    sa.Column('primary_attrib', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['primary_attrib'], ['award_grant.primary_attrib'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['proposal_application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('primary_attribution', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['primary_attribution'], ['funding.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('rc_team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_member', sa.Integer(), nullable=False),
    sa.Column('team_member_position', sa.String(length=70), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('co_pi', sa.Boolean(), nullable=False),
    sa.Column('pi', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['rc_team.team_id'], ),
    sa.ForeignKeyConstraint(['team_member'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('theme_critique', sa.Text(), nullable=False),
    sa.Column('theme_name', sa.String(length=100), nullable=False),
    sa.Column('theme_rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.ForeignKeyConstraint(['theme_name'], ['proposal_themes.theme_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('themes')
    op.drop_table('rc_team_members')
    op.drop_table('teams')
    op.drop_table('reviews')
    op.drop_table('rc_team')
    op.drop_table('proposal_draft')
    op.drop_table('pending_reviews')
    op.drop_table('co_applicants')
    op.drop_table('application_files')
    op.drop_table('application_collaborators')
    op.drop_table('societies')
    op.drop_table('proposal_application')
    op.drop_table('funding')
    op.drop_table('employment')
    op.drop_table('education')
    op.drop_table('awards')
    op.drop_table('award_grant')
    op.drop_table('users')
    op.drop_table('proposal_themes')
    op.drop_table('proposal_call_files')
    op.drop_table('user_types')
    op.drop_table('proposal_call')
    op.drop_table('nrp_area')
    # ### end Alembic commands ###
