"""empty message

Revision ID: b4b76ea23411
Revises: 
Create Date: 2019-01-29 13:56:43.697681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b76ea23411'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(length=25), nullable=False),
    sa.Column('l_name', sa.String(length=30), nullable=False),
    sa.Column('job_title', sa.String(length=50), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=True),
    sa.Column('suffix', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('phone_ext', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('orcid', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(length=25), nullable=False),
    sa.Column('field_of_study', sa.String(length=30), nullable=False),
    sa.Column('institution', sa.String(length=25), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('year_degree_award', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('education')
    op.drop_table('users')
    # ### end Alembic commands ###
